services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d  # Mount the init directory
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_HOST: "db:3306"
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_user_password
    ports:
      - "8080:80"


volumes:
  db_data:
