services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql  # Mount the init directory
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_HOST: "db:3306"
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_user_password
    ports:
      - "8080:80"


volumes:
  db_data:
